### ISSUE TITLE
ANN: Splitting up dataportal

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/databroker#1]
As discussed offline with some of you, it's become clear between teaching at the beamlines and overhauling the [top-level documentation](nsls-ii.github.io) that "dataportal" as an umbrella over databroker and datamuxer is confusing and adds no value.

From a developer point of view, it was convenient for us to lump them together while all three pieces (broker, muxer, replay) were evolving fast,. But now muxer and broker are really quite separate, and replay is retired. Broker and muxer have no dependencies on each other, and they provide very different functionality that is only sometimes needed together.

The dataportal package will live on as a skeleton of shims, so that all old user code will continue to work. (This is what IPython did when they split up the main package.)

**Comment by ericdill** [comment]
Do we have old user code that we care about?

**Comment by danielballan** [comment]
Up to a point. It was easy to maintain backward compatibility in this case. Many CSX notebooks use dataportal, and several people are still in the habit of using it at the beamline.

This issue was just to make a record of then plan, so I guess I'll close it. Reopen if there is more to say here.
This is not to say that it's too late to break APIs for a good reason.
