### ISSUE TITLE
Time-based search may be broken

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/databroker#102]
Could #96 have broken time-based search? The relevant test is potentially sensitive to the time of day that it is run. I notice that the time-based search happened to fail in #88 because it searched for scans between 2016-11-15 and 2016-11-16 and found none because it was still 2016-11-14 (local time) though already 2015-11-15 in Greenwich.

Either we have a timezone problem or Travis-CI was excited to celebrate my birthday a little early.

**Comment by tacaswell** [comment]
No, the changes in #96 only touch in `get_table`, the time-based search runs through https://github.com/NSLS-II/metadatastore/blob/master/metadatastore/core.py#L784 or https://github.com/NSLS-II/databroker/blob/master/databroker/broker.py#L54

**Comment by danielballan** [comment]
Superceded by #119
