### ISSUE TITLE
ENH: track databroker or (MDS/FS) upon header return

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/databroker#104]
It might be extremely useful to include some sort of database identifying uid(s) (or connection information?) in the returned headers, that way we could access the database that the header came from only knowing the header. An example of this is getting all the events from an otherwise unknown databroker given the header.

Moved from NSLS-II/metadatastore#260

**Comment by danielballan** [comment]
As currently factored there is no nice way to customize what is in the header. The code could and probably should be refactored so that subclasses can do this.

**Comment by CJ-Wright** [comment]
Actually I have found a temp fix. The current plan is to load all the raw data into the analysis databroker. We'll keep the exp data in a backup db just in case we blow something up. This way we only have one databroker to talk to at a time. Long term it would be good to have though

**Comment by CJ-Wright** [comment]
I think this has been fixed by #107
