### ISSUE TITLE
python interactive environment problem

### ISSUE THREAD

**Issue by xiaojinghuang** [NSLS-II/databroker#105]
Inside an iterative calculation loop, the current result is displayed using plt.imshow(), plt.show(), plt.draw() commands. It work in regular ipython environment. When switch to 'analysis' environment in order to extract data through databroker, the live display function fails to refresh the image during iteration. It pops a blank window, and wait until the calculation finishes to display it.

Do you know what causes this problem? Thank you.

**Comment by hhslepicka** [comment]
@xiaojinghuang 
Please check if you have the call to ```install_qt_kicker``` in your profile_analysis startup code.

**Comment by licode** [comment]
@xiaojinghuang , can you wrap up a simple python example and send it to me? I will play with it at analysis environment, and check what's the issue.

**Comment by xiaojinghuang** [comment]
@licode , could you please try this?
a=np.zeros((10,10))
for i in range(5):
    plt.figure(1)
    a[:i,:i] = 1
    plt.imshow(a)
    plt.title(np.str(i))
    plt.show()
    plt.draw()
    time.sleep(2)

**Comment by licode** [comment]
@xiaojinghuang try something like this. I think you are using an old version of matplotlib
```
import numpy as np
import matplotlib.pyplot as plt

plt.figure(1)
plt.ion()
a=np.zeros((10,10))

for i in range(10):
    a[:i,:i] = 1
    plt.imshow(a)
    plt.title(np.str(i))
    plt.pause(0.5)
```

**Comment by xiaojinghuang** [comment]
@licode plt.ion() works for the test purpose, but it doesn't work for my code. If you have time, could you please drop by 3ID? I can show you. Thank you.

**Comment by licode** [comment]
Sure. I will talk to you today.

**Comment by arkilic** [comment]
@licode I think @hhslepicka is right. We had the same issue in AMX, `install_qt_kicker` did the trick

**Comment by licode** [comment]
I tried it at bluesky env, but still doesn't work. 

```
%matplotlib qt
from bluesky.utils import install_qt_kickcer
install_qt_kicker()

import numpy as np
import matplotlib.pyplot as plt
import time

a=np.zeros((10,10))
for i in range(5):
    plt.figure(1)
    a[:i,:i] = 1
    plt.imshow(a)
    plt.title(np.str(i))
    plt.show()
    plt.draw()
    time.sleep(2)
```

The plot only shows in the end.

**Comment by arkilic** [comment]
Could you check this out?
https://github.com/NSLS-II-FMX/profile_collection/blob/bf51b7da360641e78d7ab027dde4e49f0611569f/startup/01-bluesky.py#L11-L21

**Comment by arkilic** [comment]
it's gotta be 'install_nb_kicker', not 'install_qt_kicker'

**Comment by licode** [comment]
ok, if I change time.sleep(2) to plt.pause(2), it works.

**Comment by arkilic** [comment]
Since ipython, use qt_kicker.

**Comment by xiaojinghuang** [comment]
@licode plt.pause() fixes the problem. Thank you very much. Your prompt help is greatly appreciated.

**Comment by tacaswell** [comment]
If you use `time.sleep` the python process sleeps meaning it does nothing (you should almost never use sleep).

If you use `plt.pause`, the GUI event loop is run for the specified amount of time (which keeps the figures interactive) but still pauses your computation.
