### ISSUE TITLE
databroker returns error on searchs earlier than 2015-10-24

### ISSUE THREAD

**Issue by chiahaoliu** [NSLS-II/databroker#11]
As I noticed, some changes seem to happen just now. An hour ago, databorker worked normally as I can trace back to 2015-09, but now it returns error message after I go earlier than 2015-10-24

screenshot is attached here
![image](https://cloud.githubusercontent.com/assets/15218640/10808372/15b2a896-7dc1-11e5-9028-381fd0583d2a.png)

**Comment by tacaswell** [comment]
try re-starting your ipython session.  That looks like there is an issue in the caching layer.

**Comment by tacaswell** [comment]
@chiahaoliu Did restarting help?

**Comment by chiahaoliu** [comment]
@tacaswell  Yes, it solved my problem immediately, thanks! Sorry I should have replied right away after I finished
