### ISSUE TITLE
list of headers should be reversed

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/databroker#126]
The list of headers should be reversed, currently they are in chronological order.
This means that `db[-1]` and `db()[-1]` give back different answers, this is confusing.

**Comment by tacaswell** [comment]
I think this is a bug in portable mds, they should be coming out in ascending time order.

**Comment by CJ-Wright** [comment]
I think I was getting this from the mongo backed system.

**Comment by CJ-Wright** [comment]
Closing as a feature not bug
