### ISSUE TITLE
Restore _repr_html_ on new implementation of Header

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/databroker#133]
It got deleted in the refactor.

**Comment by danielballan** [comment]
Actually this lives in doct; I don't think it was deleted after all. @tacaswell, I originally opened this issue because you mentioned it on GChat. Please re-open if I'm wrong about this.

**Comment by tacaswell** [comment]
Header isn't a Document anymore

**Comment by danielballan** [comment]
I was wrong! `header.start` still pretty-prints, but `header` does not.
