### ISSUE TITLE
Discussion: should we have coverage on tests?

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/databroker#134]
My argument is yes we should. Testing is very important and doubly so that all the test code gets written. Consider the following test:
```python
def test_iter():
    a  = db.restream(hdr)
    for b in a:
        assert something
```
This test will not fail if a is empty, we will simply miss the assert. One way to deal with this is to throw a known fail into the code, run it, check that it failed, then remove it because it is messy. Another way to deal with this would be to run coverage on the test code. Coverage would show that the for loop line was ran but none of the internals were executed thus hinting to us that the internal asserts are not being tested.

One potential solution is to run coverage twice, one without the test code (for our line tallys) and one with the tests covered to test the health of the test codebase.

**Comment by CJ-Wright** [comment]
In conversation with @danielballan

**Comment by tacaswell** [comment]
Yes we should have coverage on the tests and you can configure codecov to enforce a different coverage fraction on the tests that the code base (should be 100%).

**Comment by danielballan** [comment]
Great! I was not aware this was possible. Let's do it.

**Comment by CJ-Wright** [comment]
Can we just modify the .coveragerc?

**Comment by tacaswell** [comment]
matplotlib master is set up like this, have a look at that.
