### ISSUE TITLE
db.__call__ return a result proxy?

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/databroker#135]
It's becoming pretty common for queries to return large results sets that take a long time to return. We might want to change `db.__call__` to return a result proxy that needs to be fetched like `db(**query).fetch()`. In early days we were reluctant to do that in the original pass because we were getting pushback on the verbosity of the API, but ultimately I think that was the wrong call. Returning a result proxy would make things fast and also allow us to incorporate things like `limit` which are hard to fit into our elided query API.

I think we can leave `db.__getitem__` as it is because those query results sets scale with the size of the input argument. Since that's the API that people use the most, this might not even break very much user code. Of course it will break some.

**Comment by tacaswell** [comment]
Could we just change `__call__` to be a generator?

**Comment by danielballan** [comment]
I've been thinking about that, and I think that we should considering following other db libs in making it a special object, upon which you can call methods like `order_by` and, ultimately, `fetch`. A generator would be nice but we should weigh it against lost flexibility.

**Comment by tacaswell** [comment]
on the other hand, the `__call__` is going to be used interactively a lot, we should reduce the friction on that.

We probably should add a method like `query` that returns that proxy object and `__call__` is just a convience for `db.query(...).fetch()`.
