### ISSUE TITLE
Summary of db and mds changes considered

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/databroker#136]
*An issue for tracking the API-breaking changes being considered in databroker and related libs*

To improve performance:
* [x] Break `db.__call__` API to return a generator or some generator-like lazy iterable

To make documents from RE and db match exactly:
* [x] Do not dereference by default. That is, currently `header.descriptors[0].start == header.start` but we would change to `header.descriptors[0].start == header.start.uid`. Likewise `event.descriptor` would become a uid.
* [ ] Do not fill in place by default (so that callbacks don't interfere with one another)

To avoid configuration-file spaghetti:
* [x] Break `from databroker import db` and replace it with something like `import nsls2utils; nsls2utils.get_broker('2-ID')`

**Comment by tacaswell** [comment]
Just the `__call__` change for this cycle.

**Comment by danielballan** [comment]
Bumping this issue just to say, this is still a good summary of our intentions for the upcoming release of databroker (and definitely all need to be done before 1.0).

**Comment by CJ-Wright** [comment]
What is the plan for the configuration-file break for databrokers outside of the ring?

**Comment by CJ-Wright** [comment]
:+1: on the no dereference, this is rather frustrating since the live data and the databroker don't give the same results.

**Comment by danielballan** [comment]
All except filling-in-place have been merged. That has it's own issue at https://github.com/NSLS-II/databroker/issues/129, which is already on this 0.9 milestone, so I will now close this issue.
