### ISSUE TITLE
Conda Install Issue

### ISSUE THREAD

**Issue by blaiszik** [NSLS-II/databroker#140]
We are trying to work with DataBroker for some hackathon related topics and get the following error on a relatively clean Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-59-generic x86_64) with conda version 4.3.13-py36_0. Any help is appreciated.

<<< 

$ conda install databroker -c lightsource2-tag
Fetching package metadata ...........
Solving package specifications:
PackageNotFoundError: Package not found: '' Dependencies missing in current linux-64 channels:
  - databroker -> boltons
  - databroker -> doct -> humanize
  - databroker -> doct -> prettytable
  - databroker -> filestore >=0.3.0 -> pims -> slicerator >=0.9.4
  - databroker -> filestore >=0.3.0 -> tifffile
  - databroker -> metadatastore >=0.5.1
Close matches found; did you mean one of these?
    boltons: boto
    prettytable: pytables
You can search for packages on anaconda.org with
    anaconda search -t conda tifffile
(and similarly for the other packages)

<<<

$ conda install databroker -c lightsource2-dev
Fetching package metadata ...........
Solving package specifications:
PackageNotFoundError: Package not found: '' Dependencies missing in current linux-64 channels:
  - databroker -> channelarchiver -> tzlocal
  - databroker -> filestore >=v0.2.0 -> doct -> humanize
  - databroker -> filestore >=v0.2.0 -> doct -> prettytable
  - databroker -> filestore >=v0.2.0 -> pims
  - databroker -> filestore >=v0.2.0 -> tifffile
  - databroker -> metadatastore >=v0.2.0
Close matches found; did you mean one of these?
    prettytable: pytables
You can search for packages on anaconda.org with
    anaconda search -t conda tzlocal
(and similarly for the other packages)

**Comment by stuartcampbell** [comment]
Hi Ben, 
Should I just send you my key and then I can login and fix it ? (Or try to before having to ask someone more knowledgeable! :)) 
Stu

**Comment by tacaswell** [comment]
try adding `-c conda-forge` as well.

**Comment by tacaswell** [comment]
@blaiszik did this get sorted?

**Comment by blaiszik** [comment]
Adding `-c conda-forge` didn't fix the problem. We haven't looked much deeper on this yet though. If you have any other ideas we could try, we're happy to give it a shot.

**Comment by tacaswell** [comment]
`-c soft-matter` is probably also needed (our _internal_ installation procedure is smoother I swear).

**Comment by stuartcampbell** [comment]
Having done this externally to BNL I'm still happy to help.  @blaiszik I'll slack you my public key

**Comment by blaiszik** [comment]
No luck yet. Is this what you had in mind Thomas? It looks like a different error at least. :) 

```
$ conda install databroker -c lightsource2-tag -c conda-forge -c soft-matter
Fetching package metadata ...............
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - databroker -> channelarchiver -> python 3.4*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

```
$ conda install databroker -c lightsource2-dev -c conda-forge -c soft-matter
Fetching package metadata ...............
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - databroker -> boltons -> python 3.5* -> sqlite 3.9.*
  - databroker -> boltons -> python 3.5* -> xz 5.0.*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.```

**Comment by CJ-Wright** [comment]
To the best of my knowledge `databroker` doesn't have a [3.6 packaging](https://anaconda.org/lightsource2/databroker/files) (as many things don't). You might have better luck if you downgrade your python install to python 3.5 and use the `dev` channel (or 3.4 and the `tag` channel).

**Comment by danielballan** [comment]
@blaiszik We finally got our 3.6 packaging rolled out, so this should now work. Note that we only build conda packages for Linux these days. But, in case you are interested, I believe @licode is interested in building and uploading everything for OSX soon.

**Comment by blaiszik** [comment]
Seems to work, thanks for the update @danielballan. We will play around with this and let you know how it goes!

**Comment by stuartcampbell** [comment]
@blaiszik I'm assuming this is all ok now ?  If not, please just re-open this issue.
