### ISSUE TITLE
Access convention between `db[]` and `db()`

### ISSUE THREAD

**Issue by ordirules** [NSLS-II/databroker#149]
`db[-1]` gives latest entry.
However, `db(param="foo")[-1]` gives earliest entry.

Will this continue to be the convention in databroker? Just wanted to verify.

**Comment by arkilic** [comment]
Here is the corresponding conversation: https://github.com/NSLS-II/databroker/pull/127

**Comment by ordirules** [comment]
thanks! @arkilic I'll close due to repeated issue.
