### ISSUE TITLE
ENH: add db.__version_ capability

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/databroker#152]
!conda list works on some notebook servers but not all.  No other way to determine databroker version.
@danielballan  is this possible?  it is complicated to find out the version of databroker. luckly !conda list seems to work in bluesky  (starting with bsui now)

**Comment by hhslepicka** [comment]
@ambarb , according to the [code](https://github.com/NSLS-II/databroker/blob/99cc1b1236ef32c3e6dabd92eb5a5212b0d89028/databroker/__init__.py#L28) this was supposed to work:

```python
import databroker
print(databroker.__version__)
```

**Comment by ambarb** [comment]
@hhslepicka 
Thanks for typing the commands and aiding in my re-discovery.  I forgot that it has to be strictly ````import data broker```` and not ````from data broker import DataBroker as db````.

**Comment by hhslepicka** [comment]
@ambarb no problem! I also forget about it somethimes! Glad it worked. 👍 
PS: All the packages at NSLS-II use versioneer and support this <package_name>.__version__ check.
