### ISSUE TITLE
AttributeError: module 'attr' has no attribute 's'

### ISSUE THREAD

**Issue by ordirules** [NSLS-II/databroker#154]
So there's a potential subtle error from a package conflict that might happen to outside users (I say outside because it won't happen with the right conda recipe).

Basically, if you do this:
```pip install attr```
you'll install the wrong `attr` library and see this:

```python
In [1]: import databroker

/home/lhermitte/research/projects/databroker/databroker/core.py in <module>()
     30 
     31 
---> 32 @attr.s(frozen=True)
     33 class Header(object):
     34     """A dictionary-like object summarizing metadata for a run."""

AttributeError: module 'attr' has no attribute 's'
```

The correct way to resolve this is basically:
```
pip uninstall attr
pip install attrs
```
`attr` installs `attr-0.2.0` and `attrs` installs `installed attrs-16.3.0`.

Maybe add some check or something? Figured I'd share since it's something to look out for and had me scratching my head for the past 15 min... :-|

**Comment by CJ-Wright** [comment]
Yea there is a problem with the current conda-forge standard for attrs.
https://github.com/conda-forge/attrs-feedstock/pull/1
I am working on it, although help would be appreciated.
(Something tells me that there are going to be some very chilly yaks at the end of this)

**Comment by danielballan** [comment]
As of #143, attrs should be installed when databroker is installed. Nonetheless it might be worth doing a specific check for this package at import time and providing an customized ImportError, given the weird attrs vs attr confusion.

**Comment by danielballan** [comment]
See #155

**Comment by ordirules** [comment]
`pip install attr` will still have `import attr` be successful. I don't know if that resolves it
Maybe do something like:
```python
try:
    attr.s
except AttributeError("Error wrong attr library imported. Please uninstall attr and install attrs")
```

I think could be wrong... I think this naming conflict should maybe be resolved higher up.

**Comment by tacaswell** [comment]
Closing as fixed by the requirements updates, leaving associated PR open.
