### ISSUE TITLE
method to return uids (and not headers?)

### ISSUE THREAD

**Issue by ordirules** [NSLS-II/databroker#157]
It would be nice to have the following feature:
```python
uids = db.get_uids(**search_params)
```

The motivation for this is to allow out of order accessing of data (such as random sampling). This would be useful for machine learning algorithms which could test their reliability by randomly sampling from elements stored in databroker. The metadata in the samples would be assumed to contain the information necessary with regards to the classification.

Would it be possible to support this? Or is there perhaps a better way?

thanks!

**Comment by tacaswell** [comment]
What would this provide over?

```python
uids = [h.start['uid'] for h in db(**search_params)]
```

**Comment by ordirules** [comment]
If `db(**search_params)` was a generator (which I think is your plan?), that could be okay. I'm worried about a ton of metadata being loaded in memory from a large search.
I would still vote for getting uids if not hard to do (and okay to support in future). The less data sent the better.

**Comment by tacaswell** [comment]
See https://github.com/NSLS-II/databroker/pull/158 for lazy `db()` results.

**Comment by ordirules** [comment]
thanks, I guess it should be okay. We can populate uids ourselves from there.
I said I'd vote for getting just uids but I'm ambivalent. We'll implement something first assuming generators and if it's really a problem (which likely not) I'll post another issue. 

Will this be implementable as soon as PR accepted or is this part of a larger refactoring and should we wait? (I assume yes since it's `master` branch)

**Comment by arkilic** [comment]
@ordirules if you have so many headers that it becomes an issue, mongo has means to only return uids. It is really straight forward but I doubt that @tacaswell's solution will have any issues.

**Comment by ordirules** [comment]
yeah i've interfaced mongo db directly before. sounds good, ill try that if there's an issue (but I think you're right i probably won't need this) thanks!

**Comment by tacaswell** [comment]
Closing this for now. We can re-address when we have some performance bench marks that this is an issue.
