### ISSUE TITLE
Cursor error during export

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/databroker#167]
I got the following error during export `pymongo.errors.CursorNotFound: Cursor not found, cursor id: 53407868069` Thoughts?

**Comment by tacaswell** [comment]
never seen that one before...

**Comment by CJ-Wright** [comment]
I've had it happen 3 times to me out at XPD.

**Comment by CJ-Wright** [comment]
Traceback
```python
Traceback (most recent call last):
  File "chunk_export.py", line 42, in <module>
    chunk_loop()
  File "chunk_export.py", line 18, in chunk_loop
    for i, hdr in enumerate(hdrs):
  File "/home/cwright/other_src/databroker/databroker/broker.py", line 258, in __iter__
    for start, stop in res:
  File "/home/cwright/other_src/databroker/databroker/broker.py", line 1105, in <genexpr>
    return ((s, _safe_get_stop(self, s)) for s in starts)
  File "/home/cwright/other_src/metadatastore/metadatastore/mds.py", line 422, in find_run_starts
    for rs in gen:
  File "/home/cwright/other_src/metadatastore/metadatastore/core.py", line 894, in find_run_starts
    for rs in rs_objects:
  File "/home/cwright/anaconda/envs/export/lib/python3.5/site-packages/pymongo/cursor.py", line 1090, in next
    if len(self.__data) or self._refresh():
  File "/home/cwright/anaconda/envs/export/lib/python3.5/site-packages/pymongo/cursor.py", line 1032, in _refresh
    self.__max_await_time_ms))
  File "/home/cwright/anaconda/envs/export/lib/python3.5/site-packages/pymongo/cursor.py", line 905, in __send_message
    helpers._check_command_response(doc['data'][0])
  File "/home/cwright/anaconda/envs/export/lib/python3.5/site-packages/pymongo/helpers.py", line 202, in _check_command_response
    raise CursorNotFound(errmsg, code, response)
pymongo.errors.CursorNotFound: Cursor not found, cursor id: 54045161945
```

**Comment by arkilic** [comment]
It seems like you are letting the cursor time out by not unpacking the cursor contents.

**Comment by CJ-Wright** [comment]
Could this be due to hdrs being lazy?

**Comment by arkilic** [comment]
The cursor itself is also lazy, that's the primary reason why it times out if it is not consumed before timeout.

**Comment by CJ-Wright** [comment]
What constitutes "consumed"?

**Comment by arkilic** [comment]
"Getting actual documents"

**Comment by hhslepicka** [comment]
The default timeout is 10 minutes and there is no way to change that other than remove it.

See: http://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.find

**Comment by CJ-Wright** [comment]
Here is the script I am running
```python
from databroker.databroker import DataBroker as db
from databroker import Broker
from portable_mds.sqlite.mds import MDS
# from portable_mds.mongoquery.mds import MDS
from portable_fs.sqlite.fs import FileStore
import tzlocal
import os
from sqlite3 import OperationalError

db.add_filter(bt_piLast='Billinge')
hdrs = list(db())
# test_hdrs = hdrs[-5]

root_stem = '/home/cwright/export_chunks'

def chunk_loop():
    for i in range(len(hdrs)):
        hdr = hdrs[i]
        if i%100 == 0:
            j = i//100
            os.chdir(root_stem)
            chunk_folder = os.path.join(root_stem, 'chunk_{}'.format(str(j)))
            print(chunk_folder)
            if not os.path.exists(chunk_folder):
                os.mkdir(chunk_folder)
            os.chdir(chunk_folder)
            new_mds = MDS({'directory': chunk_folder,
                           'timezone': tzlocal.get_localzone().zone}, version=1)
            new_fs = FileStore({'dbpath':os.path.join(chunk_folder, 'filestore')},
                               version=1)
            new_db = Broker(new_mds, new_fs)
        try:
            print(i, hdr.start['uid'])
            db.export(hdr, new_db, new_root=chunk_folder)
        except Exception as e:
            # We still need the power to kill this if need be
            if isinstance(e, (KeyboardInterrupt, SystemExit)):
                raise e
            # But internal errors (botched runs, etc) shouldn't stop us
            else:
                print(e)
                pass
chunk_loop()
```

**Comment by hhslepicka** [comment]
You could use the same as for the events and remove the timeout from the cursor:

https://github.com/NSLS-II/metadatastore/blob/6aa8b30480d469edfb53b355edbfa4160e84b34b/metadatastore/core.py#L1031

**Comment by arkilic** [comment]
@hhslepicka He is not using the mongo cursor, he is using the portable stuff that is sqlite.

**Comment by hhslepicka** [comment]
@arkilic not according to his error message: https://github.com/NSLS-II/databroker/issues/167#issuecomment-303775248

He probably have a lot of run_starts and the processing is taking more than 10 minutes which is causing the cursor at metadatastore to expire and result in this error.
Consistency across the use (run_start, run_stop, etc) and events would be great to avoid it.
Of course one will have way less run_starts than events or in the worst case the same amount.
If the same strategy as for events is used for the others this can be avoided.

**Comment by arkilic** [comment]
@hhslepicka Even HXN cursors that sometimes take an hour don't time out. I doubt that it is the issue. See, we have more interesting problems than SLAC

**Comment by hhslepicka** [comment]
The problem is not the time to fetch the data from the database.
The problem is the time that you leave the cursor object open without consuming all the data in it.
Probably what @CJ-Wright is running on the loop is taking more than 10 minutes to consume all the data.
@arkilic don't be lazy and change the code to use the same strategy as the one for the events. 

Here is your medal for accomplishing this task: 🥇.

Lol! I check the GitHub messages while the application builds! =(

**Comment by hhslepicka** [comment]
![muttley-picture](https://cloud.githubusercontent.com/assets/8185425/26419053/430cab40-4073-11e7-9960-dbba1041a854.gif)

**Comment by arkilic** [comment]
@hhslepicka That was exactly my point, it is the time before the cursor is consumed that causes the timeout. What is the strategy we use for events? The event cursor would also time out if you don't fetch the data for 10 minutes.

**Comment by hhslepicka** [comment]
@arkilic For events you add ```no_cursor_timeout=True``` to the find call and wrap the return of the data with a try finally block which closes the cursor.
https://github.com/NSLS-II/metadatastore/blob/6aa8b30480d469edfb53b355edbfa4160e84b34b/metadatastore/core.py#L1047

**Comment by arkilic** [comment]
That's a horrible practice that should be avoided at all cost.

**Comment by CJ-Wright** [comment]
That wasn't aimed at me right?

**Comment by hhslepicka** [comment]
Not true if you close the cursor at the end! ;)

**Comment by hhslepicka** [comment]
BTW, you added it to the events! :feelsgood: Mr. Horrible Practice
<img width="1050" alt="screen shot 2017-05-24 at 11 41 03 am" src="https://cloud.githubusercontent.com/assets/8185425/26419907/0022f502-4076-11e7-8e4d-44e518ad782a.png">

**Comment by arkilic** [comment]
I remember this convo and disagreed back then, still disagree today.

@CJ-Wright why is your application waiting for 10 minutes before it consumes the cursor?

**Comment by CJ-Wright** [comment]
Exporting is a long task. It incorporates a bunch of file copies from the nfs to local disk.

**Comment by CJ-Wright** [comment]
Note that this seemed to work if I made hdrs a list (previously it was just results)

**Comment by hhslepicka** [comment]
@CJ-Wright If you make it a list you consume the whole cursor! :neckbeard:

**Comment by CJ-Wright** [comment]
Ok, so this is a problem with the lazy results then.

**Comment by CJ-Wright** [comment]
FYI I'm running into a similar issue out at XPD this time with `hdr.documents()`
eg
```python
hdrs = list(db(some_query='yes'))
for hdr in hdrs:
    for name, doc in hdr.documents():
        run_analysis_pipeline(name, doc)
```
Is the plan to still just listify both all the headers and all their docs?
