### ISSUE TITLE
`_name` in returned docs

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/databroker#174]
Is there a way we can remove the `_name` from the documents as they are returned from `hdr.stream()`? Or can we put that in the event model spec? It is a bit annoying to have the two different systems.

**Comment by danielballan** [comment]
I agree with this actually. Our system passed the name _alongside_ the document (as in the signature of every callback) and I think `_name` is an early hack that we should consider removing.

**Comment by danielballan** [comment]
See https://nsls-ii.github.io/databroker/api.html#advanced-controlling-the-return-type

**Comment by CJ-Wright** [comment]
What does this mean concretely? Do I need to add a `prepair_hook` which strips `_name`?

**Comment by tacaswell** [comment]
Yes.

**Comment by danielballan** [comment]
I would actually say no. It means you may add a prepare_hook that never adds _name in the first place, such as the example given involving deepcopy.

**Comment by tacaswell** [comment]
Fair.
