### ISSUE TITLE
'TPX_HDF5' handler

### ISSUE THREAD

**Issue by hanfeiyan** [NSLS-II/databroker#177]
We can't retrieve image data using get_images for certain scans at 3ID. For example, I'd like to get all image data from detector 'merlin1' for scan 31505. Below is the error message.

In [3]: h=db[31505]

In [4]: images=db.get_images(h,'merlin1')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/home/hyan/python_script/my_export.py in <module>()
----> 1 images=db.get_images(h,'merlin1')

/opt/conda_envs/analysis/lib/python3.4/site-packages/databroker/broker.py in get_images(self, headers, name, handler_registry, handler_override)
    594         """
    595         return Images(self.mds, self.fs, headers, name, handler_registry,
--> 596                       handler_override)
    597 
    598     def get_resource_uids(self, header):

/opt/conda_envs/analysis/lib/python3.4/site-packages/databroker/core.py in __init__(self, mds, fs, headers, name, handler_registry, handler_override)
    555             self.handler_registry = defaultdict(lambda: handler_override)
    556         with self.fs.handler_context(self.handler_registry) as fs:
--> 557             example_frame = fs.get_datum(first_uid)
    558         # Try to duck-type as a numpy array, but fall back as a general
    559         # Python object.

/opt/conda_envs/analysis/lib/python3.4/site-packages/filestore/fs.py in retrieve(self, eid)
    174         return self._api.retrieve(self._datum_col, eid,
    175                                   self._datum_cache, self.get_spec_handler,
--> 176                                   logger)
    177 
    178     # back compat

/opt/conda_envs/analysis/lib/python3.4/site-packages/filestore/core.py in retrieve(col, eid, datum_cache, get_spec_handler, logger)
     66 def retrieve(col, eid, datum_cache, get_spec_handler, logger):
     67     datum = _get_datum_from_eid(col, eid, datum_cache, logger)
---> 68     handler = get_spec_handler(datum['resource'])
     69     return handler(**datum['datum_kwargs'])
     70 

/opt/conda_envs/analysis/lib/python3.4/site-packages/filestore/fs.py in get_spec_handler(self, resource)
    295 
    296         spec = resource['spec']
--> 297         handler = self.handler_reg[spec]
    298 
    299         key = (str(resource['uid']), handler.__name__)

/opt/conda_envs/analysis/lib/python3.4/collections/__init__.py in __getitem__(self, key)
    803             except KeyError:
    804                 pass
--> 805         return self.__missing__(key)            # support subclasses that define __missing__
    806 
    807     def get(self, key, default=None):

/opt/conda_envs/analysis/lib/python3.4/collections/__init__.py in __missing__(self, key)
    795 
    796     def __missing__(self, key):
--> 797         raise KeyError(key)
    798 
    799     def __getitem__(self, key):

KeyError: 'TPX_HDF5'

We have a timepix detector but it is not enabled in the scan. Not sure it it is related.

**Comment by licode** [comment]
handler needs to be added. working on this...

**Comment by tacaswell** [comment]
Closing as this is a configuration issue at HXN.
