### ISSUE TITLE
Tag v0.4.0

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/databroker#25]
metadatastore.doc no longer exists. Need to tag a new release on this and metadatastore

**Comment by danielballan** [comment]
Given that the metadatastore -> metadataclient migration is still slated for this cycle, v0.4.0 should probably include @tacaswell's forthcoming (non-API-breaking) rewrite that can talk to either MDS or MDC. And it would be nice if it also included the ability to find configuration fields that are now being stored in Documents by bluesky. I'm working on the latter.
