### ISSUE TITLE
Change how we package runs with no RunStop document into a Header.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/databroker#35]
Currently, if a run has no run stop (which means something went *seriously* wrong during a scan) we set `header['stop'] = None`. This leads to some annoying checks throughout the codebase. Simply leaving off the `'stop'` key such that `header['stop']` raises a `KeyError` would actually be simpler.

**Comment by ericdill** [comment]
:+1:

**Comment by danielballan** [comment]
Any objections?

**Comment by arkilic** [comment]
Nope

**Comment by klauer** [comment]
:+1:

**Comment by tacaswell** [comment]
Should `header.stop` raise `KeyError` or `AttributeError`?

**Comment by danielballan** [comment]
@tacaswell I would lean toward AttributeError, but that's up to doct, not databroker.

**Comment by danielballan** [comment]
Closed by #56
