### ISSUE TITLE
Remove channelarchiver from this project until we actually implement it

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/databroker#38]
Right now channelarchiver is in a number of installation places (travis, conda recipe) and the watermark function in utils.py, but it is not actually used anywhere in the `databroker` package.

```
$ git grep channelarchiver
.travis.yml:  # conda-forge is activated on metadatastore, filestore and channelarchiver
.travis.yml:  # - conda install -n testenv metadatastore filestore channelarchiver
.travis.yml:  - pip install https://github.com/NSLS-II/channelarchiver/zipball/master#egg=channelarchiver
README.rst:- channelarchiver
conda-recipe/meta.yaml:    - channelarchiver
databroker/utils/diagnostics.py:                'channelarchiver', 'xray_vision']
```

I would advocate for removing it until we actually use it in this project...

**Comment by danielballan** [comment]
There has been a (modest) uptick in demands to implement this. I bet we'll get to it in time for the next cycle. My two cents: save yourself the trouble of removing it and putting it back in a couple weeks.

**Comment by ericdill** [comment]
Fair enough. It has just been somewhat of a pain to keep having to build channelarchiver since we are not actually using it yet.  If we are expecting to implement this for cycle 2 of 2016, I'm fine with leaving it in

**Comment by danielballan** [comment]
Update: yet more demands for channelarchiver integration have come in. Work is underway. Closing this.
