### ISSUE TITLE
Background/Calibration handeling

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/databroker#45]
Two issues which might need to be in MDS but I am not certain.
 1. How to associate calibration data with actual data
 1. How to associate background data with actual data

Both these are issues because they might be performed at any point during your total beamtime but need to be associated with all your data. Also the calibration/background might be different for different samples/runs. Finally, calibration data is most useful in the form of (at least for XPD) a dictionary of distances and detector angles, it would be very tedious (without an auto calibrator) to need to calibrate every time you touch your data. Thus it would be great to store this processed data with the calibration data somehow.

Thoughts?

**Comment by CJ-Wright** [comment]
In discussion with @ericdill 
Potential solution is to add a 'calibration' then take that uuid and put it somewhere in the run_start document of the actual runs with the outcome of the calibration (dict of sample_to_detector_distance etc) in the event of taking the calibration image.

**Comment by danielballan** [comment]
Not too dissimilar from the code I wrote for XPD users while you were visiting: https://gist.github.com/danielballan/ad3af822a71aa41d1db9

Each run gets a `dark_frame` field in its metadata containing the uid of a run that captures a dark frame.

**Comment by CJ-Wright** [comment]
Ah, yes the only problem is that the dark_frame is almost always taken before the actual data. In this case everything could be not in order.

**Comment by danielballan** [comment]
In that case I think the association should be made in an external database that matches light frame scans to dark frame scans.

**Comment by CJ-Wright** [comment]
@danielballan I think you make a good point, if DB and MDS are all about capturing everything on the beamline and exposing it to the user, we might want some sort of bridging database which holds associations of runs (backgrounds, calibrations, and experimental data) before we start the analysis. (My understanding is that analysisstore is mostly for the reproduction of analysis routines, not the tying of data together)

**Comment by danielballan** [comment]
Yes, that sounds right to me.
