### ISSUE TITLE
filter get_events

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/databroker#49]
Would it be possible to add a kwarg to filter the output of get_events?
I know that it can be done via list comprehension but that kinda defeats the purpose of having get_events as a generator.

**Comment by CJ-Wright** [comment]
Thanks to @danielballan for this:
```python
filtered_events = (fill_event(ev) for ev in get_events(..., fill=False) if ...)
```

**Comment by danielballan** [comment]
I wasn't quite right. `fill_event` modifies in place and returns nothing, so this is not possible in one line.

```python
def get_filtered_events(*args, **kwargs):
     for ev for ev in get_events(*args, fill=False, **kwargs):
        if ...:
            fill_event(ev)
            yield ev
```

This suggests to me that it would be better if `fill_event` returned the instance of the event that it modified in place. Recent discussion has indicated that `fill_event` is problematic in other ways as well -- maybe needs a re-think.

**Comment by CJ-Wright** [comment]
```python
def get_filtered_events(*args, **kwargs):
     for ev in get_events(*args, fill=False, **kwargs):
        if ...:
            fill_event(ev)
            yield ev
```
I think this might work better

**Comment by danielballan** [comment]
Ha yes. My stutter-y syntax error was left an exercise to the reader. ;- )

**Comment by CJ-Wright** [comment]
It's ok my Bayesian filter was on.
