### ISSUE TITLE
Implement a 'watch' method that yields new documents by polling

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/databroker#65]
Recall the [zmq-based subscribe PR in bluesky](https://github.com/NSLS-II/bluesky/pull/395) (not to be confused with the zmq-based "RunEngine as a service"). The RunEngine pushes documents to a central hub which (caches them and) pushes them to consumers over the network:

``` python
for name, doc in subscribe(host):
    do_stuff(name, doc)
```

As a complement to this (as discussed offline), we need:

``` python
for name, doc in db.watch(optional_query_to_narrow_results):
    do_stuff(name, doc)
```

This addresses one of @klauer's concerns with https://github.com/NSLS-II/bluesky/pull/395 : what happens if the user forgets to configure the zmq stuff until after the scan has started? I am personally against a hybrid solution that was once discussed: to pull from databroker to "catch up" and then subscribe to pushes from zmq. But I think having a puller is a good idea, and if someone wanted to build a smart hybrid from these two pieces, they could.

Details to be worked out:
- What happens if `db` is receiving documents from more than one RunEngine at a time? Maybe the RunEngine should insert its hostname + process number + Python ojbect id into the RunStart so that the search query can watch RunEngine instance at a time, if needed.
- How frequent to do the polling? Proposal: multiply polling interval 2 if you don't see a new document on the first try; divide by 2 if you do.

**Comment by tacaswell** [comment]
@licode is working on a message bus, closing this.
